"use client";
import React, { useState, useEffect } from 'react';
import Sidebar from '@/components/Sidebar';
import { useRouter } from 'next/navigation';
import { Zap, ArrowUpRight, ArrowDownRight, Info, Clock, CheckCircle2 } from 'lucide-react';

const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000/api';

export default function SignalsPage() {
    const [signals, setSignals] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);
    const router = useRouter();

    useEffect(() => {
        const token = localStorage.getItem('aura_token');
        if (!token) {
            router.push('/login');
            return;
        }

        const getAuthHeaders = () => {
            return {
                'Authorization': `Bearer ${token}`,
                'Content-Type': 'application/json'
            };
        };

        const fetchSignals = async () => {
            try {
                const res = await fetch(`${API_BASE_URL}/signals`, {
                    headers: getAuthHeaders()
                });
                if (res.status === 401) return router.push('/login');
                const data = await res.json();
                setSignals(Array.isArray(data) ? data : []);
                setLoading(false);
            } catch (error) {
                console.error("Failed to fetch signals:", error);
                setSignals([]);
                setLoading(false);
            }
        };

        fetchSignals();
    }, []);

    return (
        <div className="flex min-h-screen">
            <Sidebar />

            <main className="flex-1 ml-64 p-10">
                <header className="flex justify-between items-center mb-10">
                    <div>
                        <h1 className="text-3xl font-bold tracking-tight mb-1">AI Signals</h1>
                        <p className="text-muted">Real-time trading opportunities generated by Aura Engine v2.</p>
                    </div>
                </header>

                {loading ? (
                    <div className="flex h-64 items-center justify-center text-muted">Calculating target entry points...</div>
                ) : (
                    <div className="space-y-6">
                        {signals.length > 0 ? signals.map((signal) => (
                            <div key={signal.id} className="glass-card flex flex-col md:flex-row gap-8 items-center group hover:border-accent/40 transition-all">
                                <div className={`w-16 h-16 rounded-2xl flex items-center justify-center shrink-0 ${signal.type === 'buy' ? 'bg-success/10 text-success' : 'bg-danger/10 text-danger'}`}>
                                    {signal.type === 'buy' ? <ArrowUpRight size={32} /> : <ArrowDownRight size={32} />}
                                </div>

                                <div className="flex-1 space-y-2 text-center md:text-left">
                                    <div className="flex items-center gap-3 justify-center md:justify-start">
                                        <h3 className="text-2xl font-black tracking-tight">{signal.symbol}</h3>
                                        <span className={`px-2.5 py-0.5 rounded-lg text-xs font-bold uppercase ${signal.confidence === 'MOONSHOT' ? 'bg-accent text-white animate-pulse' : 'bg-card-border text-foreground'
                                            }`}>
                                            {signal.confidence} Confidence
                                        </span>
                                    </div>
                                    <div className="flex items-center gap-4 text-sm text-muted justify-center md:justify-start">
                                        <div className="flex items-center gap-1">
                                            <Clock size={14} />
                                            <span>{new Date(signal.timestamp).toLocaleTimeString()}</span>
                                        </div>
                                        <div className="flex items-center gap-1">
                                            <Zap size={14} className="text-accent" />
                                            <span>Strength: {Math.round(signal.strength * 100)}%</span>
                                        </div>
                                    </div>
                                    <p className="text-foreground/80 font-medium max-w-2xl">{signal.logic}</p>
                                </div>

                                <div className="flex flex-col gap-3 min-w-[200px] w-full md:w-auto">
                                    <button className="btn-primary flex items-center justify-center gap-2">
                                        Execute Signal
                                    </button>
                                    <button className="px-4 py-2 rounded-xl text-sm font-bold border border-card-border hover:bg-card flex items-center justify-center gap-2 transition-all text-muted">
                                        <Info size={16} />
                                        Full Report
                                    </button>
                                </div>
                            </div>
                        )) : (
                            <div className="glass-card p-10 text-center text-muted">
                                No active signals found at this moment.
                            </div>
                        )}

                        <div className="bg-card/30 border border-dashed border-card-border rounded-2xl p-10 text-center flex flex-col items-center">
                            <CheckCircle2 className="text-muted mb-4" size={48} />
                            <h4 className="text-xl font-bold mb-1">Aura Engine is Scanning...</h4>
                            <p className="text-muted text-sm">Monitoring 250+ pairs for breakouts and hype surges.</p>
                        </div>
                    </div>
                )}
            </main>
        </div>
    );
}
